### PR TITLE
Welcome message to any user joining the team

### PR DESCRIPTION
**Pull request by youknowriad**
Voilà mnt ce qu'il dit quand on s'inscrit

screen shot 2017-01-13 at 13 44 23

### CODE REVIEW

**Comment by IOAyman** [comment]
Let's test this first with a fake account :)

**Review by IOAyman — CHANGES_REQUESTED** [review]
Something's wrong. [Not working](https://algeriatech.slack.com/archives/test-bot/p1484313584000070)

**Comment by IOAyman** [comment]
>In order to guarantee the order in which your messages arrive, Botkit supports an optional delivery confirmation requirement [....](https://github.com/howdyai/botkit/blob/master/readme-slack.md#require-delivery-confirmation-for-rtm-messages)

You may consider enabling the [`require_delivery`](https://github.com/IOAyman/dz-community-bot/pull/5/files#diff-b87aa1ede05406f7bcd891dd0c00d596R18) then 😉

**Comment by youknowriad** [comment]
@IOAyman Why are you saying that. Are you receiving the messages in the wrong order ?

**Comment by IOAyman** [comment]
Nope. But I've read somewhere in the docs that Slack API has some delays sometimes ... It's just a safety switch

**Review by IOAyman — APPROVED** [review]
I have two confirmations from two different new members that they received the message 👍

**Comment by IOAyman** [comment]
Please alter the `greetings` controller accordingly.

**Pull request merged**
